@extends('layouts.app')

@section('content')
    @guest
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-body">
                            Hello! Please <a href="{{ route('login') }}">{{ __('Login') }}</a> first!
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div id='app-mount-root'></div>
        @include('js-bundles-autogenerated')
    @endguest
@endsection
